# Generated by Django 3.0.3 on 2020-03-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=1)),
                ('the_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_passwords', to='first_app.User')),
            ],
        ),
    ]
